# Generated by Django 5.2.17 on 2026-09-26 15:09

import datetime
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DeliverySettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "store_lat",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("22.303894"), max_digits=9
                    ),
                ),
                (
                    "store_lng",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("70.802160"), max_digits=9
                    ),
                ),
                (
                    "radius_km",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("15"), max_digits=5
                    ),
                ),
                (
                    "polygon",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Optional service boundary: list of [lat, lng] points",
                    ),
                ),
                ("enforce_pincodes", models.BooleanField(default=True)),
                (
                    "road_factor",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("1.30"), max_digits=4
                    ),
                ),
                (
                    "min_order_value",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("99"), max_digits=8
                    ),
                ),
                (
                    "small_order_below",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("199"), max_digits=8
                    ),
                ),
                (
                    "small_order_fee",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("15"), max_digits=6
                    ),
                ),
                (
                    "free_near_threshold",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("499"), max_digits=8
                    ),
                ),
                (
                    "free_near_max_km",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("6"), max_digits=5
                    ),
                ),
                (
                    "free_anywhere_threshold",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("799"), max_digits=8
                    ),
                ),
                (
                    "cod_limit",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("2000"), max_digits=8
                    ),
                ),
                ("late_night_enabled", models.BooleanField(default=False)),
                ("late_night_after", models.TimeField(default=datetime.time(22, 0))),
                (
                    "late_night_fee",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("10"), max_digits=6
                    ),
                ),
                (
                    "rain_peak_enabled",
                    models.BooleanField(
                        default=False, help_text="Switch on during rain or peak hours"
                    ),
                ),
                (
                    "rain_peak_fee",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("10"), max_digits=6
                    ),
                ),
                ("asap_min_minutes", models.PositiveSmallIntegerField(default=30)),
                ("asap_max_minutes", models.PositiveSmallIntegerField(default=60)),
                ("fast_promise_minutes", models.PositiveSmallIntegerField(default=30)),
                ("slot_minutes", models.PositiveSmallIntegerField(default=60)),
                ("slot_days_ahead", models.PositiveSmallIntegerField(default=2)),
                ("delivery_otp_enabled", models.BooleanField(default=True)),
                (
                    "rider_pay_per_order",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("25"), max_digits=6
                    ),
                ),
                (
                    "fuel_cost_per_km",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("3.50"), max_digits=5
                    ),
                ),
                (
                    "packaging_per_order",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("5"), max_digits=5
                    ),
                ),
            ],
            options={
                "verbose_name": "Delivery settings",
            },
        ),
        migrations.CreateModel(
            name="FeeSlab",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("min_km", models.DecimalField(decimal_places=2, max_digits=5)),
                ("max_km", models.DecimalField(decimal_places=2, max_digits=5)),
                ("fee", models.DecimalField(decimal_places=2, max_digits=6)),
            ],
            options={
                "ordering": ["min_km"],
            },
        ),
        migrations.CreateModel(
            name="Holiday",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                ("note", models.CharField(blank=True, max_length=80)),
            ],
            options={
                "ordering": ["date"],
            },
        ),
        migrations.CreateModel(
            name="Rider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("phone", models.CharField(max_length=15)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="ServicePincode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=6, unique=True)),
                ("area", models.CharField(blank=True, max_length=120)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "fast_delivery",
                    models.BooleanField(
                        default=False, help_text="Eligible for the 30-minute promise"
                    ),
                ),
                ("cod_blocked", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="StoreHours",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weekday",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Monday"),
                            (1, "Tuesday"),
                            (2, "Wednesday"),
                            (3, "Thursday"),
                            (4, "Friday"),
                            (5, "Saturday"),
                            (6, "Sunday"),
                        ],
                        unique=True,
                    ),
                ),
                ("opens", models.TimeField(default=datetime.time(8, 0))),
                ("closes", models.TimeField(default=datetime.time(23, 0))),
                ("is_closed", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name_plural": "store hours",
                "ordering": ["weekday"],
            },
        ),
    ]
