# Generated by Django 5.2.17 on 2026-09-26 15:09

import apps.core.images
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("number", models.CharField(blank=True, max_length=20, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_payment", "Awaiting payment"),
                            ("placed", "Placed"),
                            ("confirmed", "Confirmed"),
                            ("packed", "Packed"),
                            ("out_for_delivery", "Out for delivery"),
                            ("delivered", "Delivered"),
                            ("cancelled", "Cancelled"),
                            ("payment_failed", "Payment failed"),
                            ("refunded", "Refunded"),
                        ],
                        db_index=True,
                        default="pending_payment",
                        max_length=20,
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cod", "Cash on Delivery"),
                            ("razorpay", "Razorpay (UPI / cards / netbanking)"),
                            ("stripe", "Card (Stripe)"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("paid", "Paid"),
                            ("failed", "Failed"),
                            ("cod_due", "Cash due on delivery"),
                            ("cod_collected", "Cash collected"),
                            ("partial_refund", "Partially refunded"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending",
                        max_length=15,
                    ),
                ),
                (
                    "checkout_token",
                    models.CharField(
                        help_text="Prevents double submission",
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("ship_name", models.CharField(max_length=80)),
                ("ship_phone", models.CharField(max_length=15)),
                ("ship_address", models.CharField(max_length=400)),
                ("ship_pincode", models.CharField(db_index=True, max_length=6)),
                ("ship_area", models.CharField(blank=True, max_length=120)),
                ("ship_lat", models.DecimalField(decimal_places=6, max_digits=9)),
                ("ship_lng", models.DecimalField(decimal_places=6, max_digits=9)),
                (
                    "road_km",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=6
                    ),
                ),
                ("is_asap", models.BooleanField(default=True)),
                ("slot_start", models.DateTimeField(blank=True, null=True)),
                ("slot_label", models.CharField(blank=True, max_length=80)),
                ("fast_promise", models.BooleanField(default=False)),
                (
                    "mrp_total",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=10
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=10
                    ),
                ),
                ("coupon_code", models.CharField(blank=True, max_length=30)),
                (
                    "discount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=10
                    ),
                ),
                ("coins_used", models.PositiveIntegerField(default=0)),
                (
                    "coins_value",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=10
                    ),
                ),
                (
                    "delivery_fee",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=8
                    ),
                ),
                (
                    "small_order_fee",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=8
                    ),
                ),
                (
                    "surcharge_total",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=8
                    ),
                ),
                ("surcharges", models.JSONField(blank=True, default=list)),
                (
                    "gst_total",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=10
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=10
                    ),
                ),
                (
                    "refunded_total",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=10
                    ),
                ),
                (
                    "delivery_cost",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=8
                    ),
                ),
                ("coins_earned", models.PositiveIntegerField(default=0)),
                ("rider_name", models.CharField(blank=True, max_length=80)),
                ("rider_phone", models.CharField(blank=True, max_length=15)),
                ("delivery_otp", models.CharField(blank=True, max_length=4)),
                ("customer_note", models.CharField(blank=True, max_length=300)),
                ("staff_note", models.TextField(blank=True)),
                (
                    "placed_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("cancel_reason", models.CharField(blank=True, max_length=200)),
                (
                    "source",
                    models.CharField(
                        default="web",
                        help_text="web / subscription / reorder / bulk",
                        max_length=15,
                    ),
                ),
                ("rate_email_sent", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_payment", "Awaiting payment"),
                            ("placed", "Placed"),
                            ("confirmed", "Confirmed"),
                            ("packed", "Packed"),
                            ("out_for_delivery", "Out for delivery"),
                            ("delivered", "Delivered"),
                            ("cancelled", "Cancelled"),
                            ("payment_failed", "Payment failed"),
                            ("refunded", "Refunded"),
                        ],
                        max_length=20,
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=300)),
                ("at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["at"],
            },
        ),
        migrations.CreateModel(
            name="OrderLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_name", models.CharField(max_length=120)),
                ("variant_label", models.CharField(max_length=40)),
                ("sku", models.CharField(max_length=40)),
                ("hsn_code", models.CharField(max_length=8)),
                ("gst_rate", models.DecimalField(decimal_places=2, max_digits=4)),
                ("qty", models.PositiveIntegerField()),
                ("unit_mrp", models.DecimalField(decimal_places=2, max_digits=9)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=9)),
                (
                    "unit_cost",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=9
                    ),
                ),
                ("line_total", models.DecimalField(decimal_places=2, max_digits=10)),
                ("combo_name", models.CharField(blank=True, max_length=80)),
                ("refunded_qty", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("qty", models.PositiveSmallIntegerField(default=1)),
                (
                    "frequency",
                    models.CharField(
                        choices=[("daily", "Every day"), ("weekly", "Every week")],
                        default="daily",
                        max_length=6,
                    ),
                ),
                (
                    "weekday",
                    models.PositiveSmallIntegerField(
                        blank=True, help_text="0=Monday for weekly", null=True
                    ),
                ),
                (
                    "delivery_time",
                    models.TimeField(help_text="Preferred delivery time"),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="active",
                        max_length=10,
                    ),
                ),
                ("skip_dates", models.JSONField(blank=True, default=list)),
                ("next_run", models.DateField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ThanduComplaint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "photo",
                    models.ImageField(
                        upload_to=apps.core.images.RandomUploadPath("complaints")
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=300)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("pending", "Pending review"),
                            ("approved", "Approved: coupon sent"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BulkQuote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("name", models.CharField(max_length=80)),
                ("phone", models.CharField(max_length=15)),
                ("email", models.EmailField(max_length=254)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("wedding", "Wedding / function"),
                            ("office", "Office"),
                            ("shop", "Shop / resale"),
                            ("other", "Other"),
                        ],
                        default="wedding",
                        max_length=10,
                    ),
                ),
                ("event_date", models.DateField()),
                (
                    "requirements",
                    models.TextField(
                        help_text="What do you need? e.g. 20 crates of soft drinks, 300 lassi"
                    ),
                ),
                ("budget", models.CharField(blank=True, max_length=40)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("quoted", "Quoted"),
                            ("won", "Confirmed"),
                            ("lost", "Closed"),
                        ],
                        default="new",
                        max_length=10,
                    ),
                ),
                (
                    "quoted_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("staff_note", models.TextField(blank=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
