# Generated by Django 5.2.17 on 2026-10-01 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderline',
            name='units_per_box',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
