# Generated by Django 5.2.17 on 2026-10-09 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_boxes'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderline',
            name='restocked_qty',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
