# Generated by Django 5.2.17 on 2026-09-28 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
