# Generated by Django 5.2.17 on 2026-09-26 15:09

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(unique=True)),
                ("title", models.CharField(max_length=120)),
                (
                    "body",
                    models.TextField(
                        help_text="Plain text. Blank lines start new paragraphs."
                    ),
                ),
                ("show_in_footer", models.BooleanField(default=True)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "ordering": ["sort_order", "title"],
            },
        ),
        migrations.CreateModel(
            name="StoreSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="Rasiko", max_length=80)),
                (
                    "tagline",
                    models.CharField(
                        default="Rajkot no swaad, tamare ghare.", max_length=160
                    ),
                ),
                (
                    "tagline_en",
                    models.CharField(
                        default="Rajkot's taste, at your doorstep.", max_length=160
                    ),
                ),
                ("phone", models.CharField(default="+91 00000 00000", max_length=20)),
                (
                    "email",
                    models.EmailField(default="hello@example.com", max_length=254),
                ),
                (
                    "whatsapp_number",
                    models.CharField(
                        blank=True,
                        help_text="Shop WhatsApp number with country code, digits only, e.g. 919800000000",
                        max_length=20,
                    ),
                ),
                ("address", models.TextField(default="Rajkot, Gujarat")),
                (
                    "fssai_number",
                    models.CharField(default="XXXXXXXXXXXXXX", max_length=20),
                ),
                ("gstin", models.CharField(default="24XXXXXXXXXXXXX", max_length=15)),
                ("legal_name", models.CharField(default="Rasiko", max_length=120)),
                (
                    "state_code",
                    models.CharField(
                        default="24",
                        help_text="GST state code (Gujarat = 24)",
                        max_length=2,
                    ),
                ),
                (
                    "active_gateway",
                    models.CharField(
                        choices=[
                            ("razorpay", "Razorpay"),
                            ("stripe", "Stripe"),
                            ("none", "None (Cash on Delivery only)"),
                        ],
                        default="razorpay",
                        max_length=10,
                    ),
                ),
                ("cod_enabled", models.BooleanField(default=True)),
                (
                    "auspicious_mark",
                    models.CharField(
                        choices=[
                            ("shubh_labh", "शुभ लाभ (Shubh Labh)"),
                            ("om", "ॐ (Om)"),
                            ("none", "Off"),
                        ],
                        default="shubh_labh",
                        max_length=12,
                    ),
                ),
                ("show_success_blessing", models.BooleanField(default=True)),
                (
                    "launch_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Muhurat go-live. Before this time visitors see the coming soon page.",
                        null=True,
                    ),
                ),
                (
                    "launch_message",
                    models.CharField(
                        blank=True,
                        default="Opening on an auspicious day",
                        max_length=200,
                    ),
                ),
                (
                    "coins_earn_percent",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("2.00"), max_digits=4
                    ),
                ),
                (
                    "coin_value_rupees",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("1.00"), max_digits=5
                    ),
                ),
                (
                    "max_coin_redeem_percent",
                    models.PositiveSmallIntegerField(default=20),
                ),
                ("referral_coins", models.PositiveIntegerField(default=50)),
                ("birthday_coins", models.PositiveIntegerField(default=50)),
                (
                    "thandu_coupon_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("30.00"), max_digits=7
                    ),
                ),
                (
                    "meta_description",
                    models.CharField(
                        default="Chilled juices, soft drinks, lassi and masala soda delivered across Rajkot in 30 to 60 minutes.",
                        max_length=300,
                    ),
                ),
            ],
            options={
                "verbose_name": "Store settings",
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(db_index=True, max_length=80)),
                ("object_type", models.CharField(blank=True, max_length=60)),
                ("object_id", models.CharField(blank=True, max_length=64)),
                ("summary", models.CharField(blank=True, max_length=300)),
                ("changes", models.JSONField(blank=True, default=dict)),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Integration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(unique=True)),
                ("enabled", models.BooleanField(default=False)),
                ("data_encrypted", models.TextField(blank=True, default="")),
                ("last_test_ok", models.BooleanField(blank=True, null=True)),
                ("last_test_message", models.CharField(blank=True, max_length=300)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
