# Generated by Django 5.2.17 on 2026-10-09 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='gateway_fallback_enabled',
            field=models.BooleanField(default=False, help_text='Allow the other enabled gateway when the selected gateway is disabled.'),
        ),
    ]
