# Generated by Django 5.2.17 on 2026-09-26 15:09

import apps.core.images
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        ("orders", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Combo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=80)),
                ("description", models.CharField(blank=True, max_length=200)),
                ("price", models.DecimalField(decimal_places=2, max_digits=9)),
                ("is_active", models.BooleanField(default=True)),
                ("show_on_home", models.BooleanField(default=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="HeroSlide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("heading", models.CharField(max_length=80)),
                (
                    "heading_accent",
                    models.CharField(
                        blank=True,
                        help_text="Second line in the sunrise gradient",
                        max_length=80,
                    ),
                ),
                ("subtext", models.CharField(blank=True, max_length=160)),
                ("badge", models.CharField(blank=True, max_length=60)),
                ("button_text", models.CharField(default="Shop now", max_length=30)),
                ("button_link", models.CharField(default="/", max_length=200)),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        upload_to=apps.core.images.RandomUploadPath("slides"),
                    ),
                ),
                (
                    "mobile_image",
                    models.ImageField(
                        blank=True,
                        upload_to=apps.core.images.RandomUploadPath("slides"),
                    ),
                ),
                (
                    "image_width",
                    models.PositiveIntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "image_height",
                    models.PositiveIntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "blur_color",
                    models.CharField(blank=True, editable=False, max_length=7),
                ),
                (
                    "focal_x",
                    models.PositiveSmallIntegerField(
                        default=50, help_text="Focal point % from left"
                    ),
                ),
                (
                    "focal_y",
                    models.PositiveSmallIntegerField(
                        default=50, help_text="Focal point % from top"
                    ),
                ),
                (
                    "fit",
                    models.CharField(
                        choices=[
                            ("contain", "Show whole image"),
                            ("cover", "Fill (crop around focal point)"),
                        ],
                        default="contain",
                        max_length=8,
                    ),
                ),
                (
                    "art",
                    models.CharField(
                        blank=True,
                        default="mango,cola,lemon",
                        help_text="Drink illustrations shown when there is no image",
                        max_length=40,
                    ),
                ),
                (
                    "theme",
                    models.CharField(
                        choices=[
                            ("sunrise", "Sunrise"),
                            ("green", "Tulsi"),
                            ("pink", "Kamal"),
                        ],
                        default="sunrise",
                        max_length=8,
                    ),
                ),
                ("starts_at", models.DateTimeField(blank=True, null=True)),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "ordering": ["sort_order", "pk"],
            },
        ),
        migrations.CreateModel(
            name="CoinLedger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("delta", models.IntegerField()),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("earned", "Earned on order"),
                            ("redeemed", "Used at checkout"),
                            ("referral", "Referral bonus"),
                            ("birthday", "Birthday bonus"),
                            ("festival", "Festival bonus"),
                            ("reversed", "Reversed (refund/cancel)"),
                            ("adjust", "Adjustment"),
                        ],
                        max_length=10,
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=160)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="orders.order",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coin_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ComboItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("qty", models.PositiveSmallIntegerField(default=1)),
                (
                    "combo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="promotions.combo",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.productvariant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=30, unique=True)),
                ("description", models.CharField(blank=True, max_length=160)),
                (
                    "kind",
                    models.CharField(
                        choices=[("percent", "Percentage"), ("flat", "Flat ₹")],
                        default="flat",
                        max_length=8,
                    ),
                ),
                ("value", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "max_discount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "min_order",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=8
                    ),
                ),
                ("starts_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "usage_limit",
                    models.PositiveIntegerField(
                        blank=True, help_text="Total uses allowed", null=True
                    ),
                ),
                ("per_user_limit", models.PositiveSmallIntegerField(default=1)),
                ("first_order_only", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("show_on_home", models.BooleanField(default=False)),
                (
                    "only_user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Personal coupon (e.g. Thandu guarantee)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=80)),
                (
                    "theme",
                    models.CharField(
                        choices=[
                            ("diwali", "Diwali (diyas)"),
                            ("navratri", "Navratri (garba)"),
                            ("uttarayan", "Uttarayan / Makar Sankranti (kites)"),
                            ("holi", "Holi"),
                            ("janmashtami", "Janmashtami"),
                            ("summer", "Summer (cold drinks peak)"),
                        ],
                        max_length=12,
                    ),
                ),
                ("starts_at", models.DateTimeField()),
                ("ends_at", models.DateTimeField()),
                (
                    "show_overlay",
                    models.BooleanField(
                        default=True,
                        help_text="Toran-style decoration; layout never changes",
                    ),
                ),
                ("banner_title", models.CharField(max_length=80)),
                ("banner_text", models.CharField(blank=True, max_length=160)),
                (
                    "bonus_coins",
                    models.PositiveIntegerField(
                        default=0, help_text="Festival bonus coins on delivered orders"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "coupon",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="promotions.coupon",
                    ),
                ),
            ],
            options={
                "ordering": ["-starts_at"],
            },
        ),
        migrations.CreateModel(
            name="CouponRedemption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=8)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "coupon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="redemptions",
                        to="promotions.coupon",
                    ),
                ),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coupon_redemption",
                        to="orders.order",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BulkPriceSlab",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("min_qty", models.PositiveIntegerField()),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=9)),
                (
                    "variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bulk_slabs",
                        to="catalog.productvariant",
                    ),
                ),
            ],
            options={
                "ordering": ["variant", "min_qty"],
                "unique_together": {("variant", "min_qty")},
            },
        ),
    ]
