# Generated by Django 5.2.17 on 2026-10-01 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulkpriceslab',
            name='min_qty',
            field=models.PositiveIntegerField(verbose_name='From boxes'),
        ),
        migrations.AlterField(
            model_name='bulkpriceslab',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Price per box'),
        ),
        migrations.AlterField(
            model_name='comboitem',
            name='qty',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Boxes'),
        ),
    ]
