# Generated by Django 5.2.17 on 2026-09-26 15:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("gateway", models.CharField(max_length=10)),
                (
                    "gateway_order_id",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                (
                    "gateway_payment_id",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(default="INR", max_length=3)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="created",
                        max_length=10,
                    ),
                ),
                (
                    "idempotency_key",
                    models.CharField(default=uuid.uuid4, max_length=64, unique=True),
                ),
                ("failure_reason", models.CharField(blank=True, max_length=300)),
                ("raw", models.JSONField(blank=True, default=dict)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Refund",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "lines",
                    models.JSONField(
                        blank=True, default=dict, help_text="{order_line_id: qty}"
                    ),
                ),
                ("reason", models.CharField(max_length=300)),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("gateway", "Original payment method"),
                            ("upi", "UPI (manual)"),
                            ("cash", "Cash (manual)"),
                            ("bank", "Bank transfer (manual)"),
                        ],
                        default="gateway",
                        max_length=8,
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        help_text="UPI / bank reference for manual refunds",
                        max_length=100,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                (
                    "gateway_refund_id",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                (
                    "idempotency_key",
                    models.CharField(default=uuid.uuid4, max_length=64, unique=True),
                ),
                ("restock", models.BooleanField(default=False)),
                ("failure_reason", models.CharField(blank=True, max_length=300)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="refunds",
                        to="orders.order",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="refunds",
                        to="payments.payment",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WebhookEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gateway", models.CharField(max_length=10)),
                ("event_id", models.CharField(max_length=120)),
                ("event_type", models.CharField(max_length=80)),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                ("payload", models.JSONField(default=dict)),
            ],
            options={
                "unique_together": {("gateway", "event_id")},
            },
        ),
    ]
