# Generated by Django 5.2.17 on 2026-10-09 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='creation_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='creation_uncertain',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payment',
            name='last_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='reconcile_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='refund',
            name='last_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='refund',
            name='reconcile_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='refund',
            name='restocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='refund',
            name='submission_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='refund',
            name='submission_uncertain',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='webhookevent',
            name='attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='webhookevent',
            name='last_error',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='webhookevent',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='webhookevent',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=12),
        ),
    ]
