# Generated by Django 5.2.17 on 2026-09-26 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("delta", models.IntegerField()),
                ("balance_after", models.IntegerField()),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("initial", "Initial stock"),
                            ("sale", "Sale"),
                            ("refund", "Refund restock"),
                            ("cancel", "Cancelled order restock"),
                            ("manual", "Manual adjustment"),
                            ("import", "CSV import"),
                            ("damage", "Damaged / expired"),
                        ],
                        max_length=10,
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StockReservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("qty", models.PositiveIntegerField()),
                ("expires_at", models.DateTimeField(db_index=True)),
                ("released", models.BooleanField(default=False)),
                ("committed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
