# Generated by Django 5.2.17 on 2026-09-26 15:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InsightReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "generated_at",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                ("period_days", models.PositiveSmallIntegerField(default=30)),
                ("going_well", models.JSONField(default=list)),
                ("can_be_better", models.JSONField(default=list)),
                ("actions", models.JSONField(default=list)),
                ("ai_summary", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["-generated_at"],
            },
        ),
        migrations.CreateModel(
            name="CompetitorPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("competitor", models.CharField(max_length=60)),
                ("price", models.DecimalField(decimal_places=2, max_digits=9)),
                ("note", models.CharField(blank=True, max_length=160)),
                ("noted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "noted_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="competitor_prices",
                        to="catalog.productvariant",
                    ),
                ),
            ],
            options={
                "ordering": ["-noted_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "step",
                    models.CharField(
                        choices=[
                            ("view", "View"),
                            ("cart", "Cart"),
                            ("checkout", "Checkout"),
                            ("order", "Order"),
                        ],
                        db_index=True,
                        max_length=8,
                    ),
                ),
                ("session_key", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="catalog.product",
                    ),
                ),
            ],
        ),
    ]
