# Generated by Django 5.2.17 on 2026-09-26 15:09

import apps.core.images
import django.contrib.postgres.fields
import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.contrib.postgres.operations import TrigramExtension, UnaccentExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        TrigramExtension(),
        UnaccentExtension(),
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=80, unique=True)),
                ("slug", models.SlugField(blank=True, unique=True)),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        upload_to=apps.core.images.RandomUploadPath("brands"),
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=80)),
                ("name_gu", models.CharField(blank=True, max_length=80)),
                ("name_hi", models.CharField(blank=True, max_length=80)),
                ("slug", models.SlugField(blank=True, unique=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        upload_to=apps.core.images.RandomUploadPath("categories"),
                    ),
                ),
                (
                    "tile_color",
                    models.CharField(
                        choices=[
                            ("haldi", "Light haldi"),
                            ("kamal", "Kamal"),
                            ("chandan", "Chandan"),
                            ("mitti", "Mitti"),
                            ("tulsi", "Light tulsi"),
                            ("white", "White"),
                        ],
                        default="haldi",
                        max_length=10,
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        default="bottle",
                        help_text="Illustration used when there is no image",
                        max_length=20,
                    ),
                ),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("show_in_menu", models.BooleanField(default=True)),
                ("seo_title", models.CharField(blank=True, max_length=70)),
                ("seo_description", models.CharField(blank=True, max_length=160)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="catalog.category",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "categories",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                (
                    "name_gu",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Name in Gujarati"
                    ),
                ),
                (
                    "name_hi",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Name in Hindi"
                    ),
                ),
                ("slug", models.SlugField(blank=True, max_length=80, unique=True)),
                ("short_description", models.CharField(blank=True, max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "diet",
                    models.CharField(
                        choices=[("veg", "Veg"), ("nonveg", "Non-veg")],
                        default="veg",
                        max_length=6,
                    ),
                ),
                ("ingredients", models.TextField(blank=True)),
                ("allergens", models.CharField(blank=True, max_length=200)),
                (
                    "nutrition",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='e.g. {"Energy": "45 kcal", "Sugar": "10 g"}',
                    ),
                ),
                ("shelf_life", models.CharField(blank=True, max_length=80)),
                ("storage_instructions", models.CharField(blank=True, max_length=200)),
                ("best_before_note", models.CharField(blank=True, max_length=120)),
                ("country_of_origin", models.CharField(default="India", max_length=60)),
                (
                    "tags",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=30),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "attributes",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Flexible, e.g. {"sugar_free": true}',
                    ),
                ),
                (
                    "illustration",
                    models.CharField(
                        default="bottle",
                        help_text="Drink illustration used until a photo is uploaded",
                        max_length=20,
                    ),
                ),
                (
                    "illustration_color",
                    models.CharField(default="#F4B400", max_length=7),
                ),
                ("is_featured", models.BooleanField(default=False)),
                ("is_bestseller", models.BooleanField(default=False)),
                (
                    "is_new",
                    models.BooleanField(
                        default=False, help_text="Shown in Fresh Picks"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("seo_title", models.CharField(blank=True, max_length=70)),
                ("seo_description", models.CharField(blank=True, max_length=160)),
                (
                    "rating_avg",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=3
                    ),
                ),
                ("rating_count", models.PositiveIntegerField(default=0)),
                ("sold_count", models.PositiveIntegerField(default=0)),
                (
                    "search_vector",
                    django.contrib.postgres.search.SearchVectorField(
                        editable=False, null=True
                    ),
                ),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="catalog.brand",
                    ),
                ),
                (
                    "categories",
                    models.ManyToManyField(
                        related_name="products", to="catalog.category"
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to=apps.core.images.RandomUploadPath("products")
                    ),
                ),
                ("alt", models.CharField(blank=True, max_length=120)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "pk"],
            },
        ),
        migrations.CreateModel(
            name="ProductVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "label",
                    models.CharField(
                        help_text="e.g. 250 ml, 1 L, Pack of 6", max_length=40
                    ),
                ),
                ("sku", models.CharField(max_length=40, unique=True)),
                ("barcode", models.CharField(blank=True, max_length=40)),
                (
                    "mrp",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=9,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=9,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "cost_price",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=9
                    ),
                ),
                (
                    "previous_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=9, null=True
                    ),
                ),
                ("price_changed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "gst_rate",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("12.00"), max_digits=4
                    ),
                ),
                ("hsn_code", models.CharField(default="2202", max_length=8)),
                ("volume_ml", models.PositiveIntegerField(blank=True, null=True)),
                ("weight_g", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "stock_qty",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Total quantity",
                    ),
                ),
                (
                    "reserved_qty",
                    models.PositiveIntegerField(default=0, editable=False),
                ),
                ("low_stock_threshold", models.PositiveIntegerField(default=10)),
                ("max_per_order", models.PositiveSmallIntegerField(default=24)),
                (
                    "manual_out_of_stock",
                    models.BooleanField(
                        default=False,
                        help_text="Force 'Out of stock' even with quantity",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "price"],
            },
        ),
        migrations.CreateModel(
            name="BackInStockRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("notified_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_alerts",
                        to="catalog.productvariant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RecentlyViewed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("viewed_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recently_viewed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-viewed_at"],
            },
        ),
        migrations.CreateModel(
            name="Wishlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wishlist",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="product",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="catalog_pro_search__6e8905_gin"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="backinstockrequest",
            unique_together={("variant", "email")},
        ),
        migrations.AlterUniqueTogether(
            name="recentlyviewed",
            unique_together={("user", "product")},
        ),
        migrations.AlterUniqueTogether(
            name="wishlist",
            unique_together={("user", "product")},
        ),
    ]
