# Generated by Django 5.2.17 on 2026-09-26 15:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productvariant",
            name="stock_qty",
            field=models.IntegerField(
                default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name="Total quantity"
            ),
        ),
    ]
