# Generated by Django 5.2.17 on 2026-10-01 05:40

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_stock_qty_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='units_per_box',
            field=models.PositiveSmallIntegerField(default=1, help_text='e.g. 24', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Bottles per box'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=9, verbose_name='Box cost price'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='label',
            field=models.CharField(help_text='Size of one bottle, e.g. 250 ml, 1 L', max_length=40, verbose_name='Bottle size'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='low_stock_threshold',
            field=models.PositiveIntegerField(default=10, verbose_name='Low stock alert (bottles)'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='max_per_order',
            field=models.PositiveSmallIntegerField(default=24, verbose_name='Max boxes per order'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='mrp',
            field=models.DecimalField(decimal_places=2, max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Box MRP'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Box price'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='stock_qty',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Stock (bottles)'),
        ),
    ]
