# Generated by Django 5.2.17 on 2026-10-09 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_boxes'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='responsive_images',
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
    ]
